#!/usr/bin/env python3
"""Dev-only generator for VAT ID metadata.

Emits, from the curated table in tool/data/vat-formats.json:
  - lib/src/vat_id/vat_metadata.g.dart (`part of 'vat_id.dart';`)
  - js/src/data/vat-metadata.json      (the same map as JSON)

Run:  python3 tool/gen_vat_metadata.py

Structure only. The check-digit algorithms are code, not data: they differ far
too much between member states to express in a table, and each one is
documented where it is implemented (lib/src/vat_id/vat_checks.dart and
doc/algorithms.md).

Not part of the shipped package (never imported by lib/).
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "tool", "data", "vat-formats.json")
DART_OUT = os.path.join(ROOT, "lib", "src", "vat_id", "vat_metadata.g.dart")
JSON_OUT = os.path.join(ROOT, "js", "src", "data", "vat-metadata.json")

HEADER = """// Generated by tool/gen_vat_metadata.py. Do not edit by hand.
// Structures curated from the per-country table in
// docs/business-identifiers-design.md; check digits live in vat_checks.dart.

part of 'vat_id.dart';

"""


def dart_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    return f"'{escaped}'"


def main() -> None:
    with open(SOURCE, encoding="utf-8") as f:
        raw = json.load(f)

    formats = {k: v for k, v in raw.items() if not k.startswith("_")}

    lines = [HEADER, "const Map<String, VatFormat> kVatFormats = {\n"]
    for iso2 in sorted(formats):
        m = formats[iso2]
        example = dart_string(m["example"]) if m["example"] else "null"
        lines.append(
            f"  '{iso2}': VatFormat({dart_string(m['prefix'])}, "
            f"{dart_string(m['body'])}, {m['maxLen']}, {example}),\n"
        )
    lines.append("};\n")

    os.makedirs(os.path.dirname(DART_OUT), exist_ok=True)
    with open(DART_OUT, "w", encoding="utf-8") as f:
        f.write("".join(lines))

    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(formats, f, ensure_ascii=False, separators=(",", ":"), sort_keys=True)

    print(f"wrote {len(formats)} VAT formats to {DART_OUT} and {JSON_OUT}")


if __name__ == "__main__":
    main()
