#!/usr/bin/env python3
"""Dev-only generator for IBAN metadata.

Emits lib/src/iban/iban_metadata.g.dart with two const maps:
  - kIbanBban: BBAN field offsets per country, from the SWIFT IBAN Registry
    bundled by the `schwifty` package.
  - kBanks:    country code -> national bank code -> (bank name, BIC).

Run:  python3 tool/gen_iban_metadata.py [--csv path/to/sepa-zv-vz_gesamt.csv]

Not part of the shipped package (never imported by lib/). schwifty bundles the
SWIFT IBAN Registry; the Austrian bank data is (c) Oesterreichische
Nationalbank, see the NOTICE file.
"""
from __future__ import annotations

import argparse
import csv
import io
import os
import re
import ssl
import urllib.request

import pycountry
from schwifty import registry
from schwifty.registry import Component

HERE = os.path.dirname(__file__)
ROOT = os.path.normpath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "lib", "src", "iban", "iban_metadata.g.dart")
OENB_URL = "https://www.oenb.at/docroot/downloads_observ/sepa-zv-vz_gesamt.csv"


def bban_structures() -> dict:
    """ISO2 -> dict(length, bank_start, bank_end, branch_start, branch_end).

    schwifty exposes BBAN-relative (start, end) ranges; we shift them by 4 so
    they index the full IBAN string (country code + check digits = 4 chars).
    A zero-width branch range means the country has no branch identifier.
    """
    out: dict[str, dict] = {}
    for country in pycountry.countries:
        cc = country.alpha_2
        try:
            spec = registry.get_iban_spec(cc)
        except Exception:
            continue
        pos = spec.positions
        bank = pos[Component.BANK_CODE]
        branch = pos[Component.BRANCH_CODE]
        entry = {
            "length": spec.iban_length,
            "bank_start": 4 + bank.start,
            "bank_end": 4 + bank.end,
            "branch_start": None,
            "branch_end": None,
        }
        if branch.end > branch.start:
            entry["branch_start"] = 4 + branch.start
            entry["branch_end"] = 4 + branch.end
        out[cc] = entry
    return out


def load_oenb(path: str | None) -> tuple[str, dict]:
    """Returns (snapshot_date, {BLZ: (name, bic)}) from the OeNB SEPA CSV."""
    if path:
        raw = open(path, "rb").read()
    else:
        ctx = ssl.create_default_context()
        raw = urllib.request.urlopen(OENB_URL, timeout=60, context=ctx).read()
    lines = raw.decode("latin-1").splitlines()
    date = next(
        (re.search(r"vom\s+([\d.]+)", ln).group(1)
         for ln in lines if "SEPA-Verzeichnis-Abfrage" in ln),
        "unknown",
    )
    hidx = next(i for i, ln in enumerate(lines) if ln.startswith("Kennzeichen;"))
    reader = csv.DictReader(io.StringIO("\n".join(lines[hidx:])), delimiter=";")
    banks: dict[str, tuple[str, str]] = {}
    for row in reader:
        blz = (row.get("Bankleitzahl") or "").strip()
        name = (row.get("Bankenname") or "").strip()
        swift = (row.get("SWIFT-Code") or "").strip()
        if not blz or not swift:
            continue
        bic = swift[:-3] if swift.endswith("XXX") else swift
        banks.setdefault(blz, (name, bic))
    return date, banks


def dart_str(s: str) -> str:
    """A single-quoted Dart string literal for arbitrary text."""
    return "'" + s.replace("\\", "\\\\").replace("$", "\\$").replace("'", "\\'") + "'"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", help="local OeNB CSV instead of downloading")
    args = ap.parse_args()

    structures = bban_structures()
    directories = {"AT": load_oenb(args.csv)}

    buf = io.StringIO()
    buf.write("// Generated by tool/gen_iban_metadata.py. Do not edit by hand.\n")
    buf.write("// BBAN structure: SWIFT IBAN Registry, bundled via schwifty.\n")
    at_date = directories["AT"][0]
    buf.write(f"// AT banks: OeNB SEPA directory, snapshot {at_date}.\n")
    buf.write(f"// Source: {OENB_URL} -- (c) Oesterreichische Nationalbank; see NOTICE.\n\n")
    buf.write("part of 'iban_metadata.dart';\n\n")

    buf.write("const Map<String, IbanBban> kIbanBban = {\n")
    for cc in sorted(structures):
        e = structures[cc]
        bs = "null" if e["branch_start"] is None else e["branch_start"]
        be = "null" if e["branch_end"] is None else e["branch_end"]
        buf.write(
            f"  '{cc}': IbanBban(length: {e['length']}, "
            f"bankStart: {e['bank_start']}, bankEnd: {e['bank_end']}, "
            f"branchStart: {bs}, branchEnd: {be}),\n"
        )
    buf.write("};\n\n")

    buf.write("const Map<String, Map<String, Bank>> kBanks = {\n")
    for cc in sorted(directories):
        _, banks = directories[cc]
        buf.write(f"  '{cc}': {{\n")
        for code in sorted(banks):
            name, bic = banks[code]
            buf.write(f"    '{code}': Bank({dart_str(name)}, '{bic}'),\n")
        buf.write("  },\n")
    buf.write("};\n")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(buf.getvalue())
    counts = ", ".join(f"{cc}={len(directories[cc][1])}" for cc in sorted(directories))
    print(f"Wrote {OUT}: {len(structures)} countries; banks {counts}")


if __name__ == "__main__":
    main()
