// Generated by tool/gen_vat_metadata.py. Do not edit by hand.
// Structures curated from the per-country table in
// docs/business-identifiers-design.md; check digits live in vat_checks.dart.

part of 'vat_id.dart';

const Map<String, VatFormat> kVatFormats = {
  'AT': VatFormat('ATU', '^[0-9]{8}\$', 8, 'ATU16210507'),
  'BE': VatFormat('BE', '^[01][0-9]{9}\$', 10, 'BE0417497106'),
  'BG': VatFormat('BG', '^[0-9]{9,10}\$', 10, 'BG175074752'),
  'CH': VatFormat('CHE', '^[0-9]{9}\$', 9, 'CHE116281710'),
  'CY': VatFormat('CY', '^[0-9]{8}[A-Z]\$', 9, 'CY10259033P'),
  'CZ': VatFormat('CZ', '^[0-9]{8,10}\$', 10, 'CZ00177041'),
  'DE': VatFormat('DE', '^[0-9]{9}\$', 9, 'DE129274202'),
  'DK': VatFormat('DK', '^[0-9]{8}\$', 8, 'DK13585628'),
  'EE': VatFormat('EE', '^[0-9]{9}\$', 9, 'EE100594102'),
  'ES': VatFormat('ES', '^[A-Z0-9][0-9]{7}[A-Z0-9]\$', 9, 'ESA28015865'),
  'FI': VatFormat('FI', '^[0-9]{8}\$', 8, 'FI20774740'),
  'FR': VatFormat('FR', '^[0-9A-HJ-NP-Z]{2}[0-9]{9}\$', 11, 'FR84919434894'),
  'GB': VatFormat('GB', '^([0-9]{9}|[0-9]{12}|GD[0-9]{3}|HA[0-9]{3}|(GD|HA)8888[0-9]{5})\$', 12, 'GB220430231'),
  'GR': VatFormat('EL', '^[0-9]{9}\$', 9, 'EL094259216'),
  'HR': VatFormat('HR', '^[0-9]{11}\$', 11, 'HR33392005961'),
  'HU': VatFormat('HU', '^[0-9]{8}\$', 8, 'HU10625790'),
  'IE': VatFormat('IE', '^([0-9]{7}[A-W]|[0-9][A-Z*+][0-9]{5}[A-W]|[0-9]{7}[A-W][A-IW])\$', 9, 'IE4749148U'),
  'IT': VatFormat('IT', '^[0-9]{11}\$', 11, 'IT03656470360'),
  'LT': VatFormat('LT', '^([0-9]{9}|[0-9]{12})\$', 12, 'LT119511515'),
  'LU': VatFormat('LU', '^[0-9]{8}\$', 8, 'LU15027442'),
  'LV': VatFormat('LV', '^[0-9]{11}\$', 11, 'LV40003032949'),
  'MT': VatFormat('MT', '^[0-9]{8}\$', 8, 'MT11679112'),
  'NL': VatFormat('NL', '^[0-9]{9}B[0-9]{2}\$', 12, 'NL002455799B11'),
  'NO': VatFormat('NO', '^[0-9]{9}MVA\$', 12, 'NO995525828MVA'),
  'PL': VatFormat('PL', '^[0-9]{10}\$', 10, 'PL7742372663'),
  'PT': VatFormat('PT', '^[0-9]{9}\$', 9, 'PT505060515'),
  'RO': VatFormat('RO', '^[0-9]{2,10}\$', 10, 'RO18547290'),
  'RS': VatFormat('RS', '^[0-9]{9}\$', 9, 'RS101134702'),
  'SE': VatFormat('SE', '^[0-9]{12}\$', 12, 'SE556034348401'),
  'SI': VatFormat('SI', '^[0-9]{8}\$', 8, 'SI82646716'),
  'SK': VatFormat('SK', '^[0-9]{10}\$', 10, 'SK7120001713'),
  'TR': VatFormat('TR', '^[0-9]{10}\$', 10, 'TR4540536920'),
  'XI': VatFormat('XI', '^([0-9]{9}|[0-9]{12}|GD[0-9]{3}|HA[0-9]{3}|(GD|HA)8888[0-9]{5})\$', 12, null),
};
