// Generated by tool/gen_vat_metadata.py. Do not edit by hand.
// Structures curated from the per-country table in
// docs/business-identifiers-design.md; check digits live in vat_checks.dart.

part of 'vat_id.dart';

const Map<String, VatFormat> kVatFormats = {
  'AT': VatFormat('ATU', '^[0-9]{8}\$', 8, 'ATU16210507'),
  'BE': VatFormat('BE', '^[01][0-9]{9}\$', 10, null),
  'BG': VatFormat('BG', '^[0-9]{9,10}\$', 10, null),
  'CH': VatFormat('CHE', '^[0-9]{9}\$', 9, null),
  'CY': VatFormat('CY', '^[0-9]{8}[A-Z]\$', 9, null),
  'CZ': VatFormat('CZ', '^[0-9]{8,10}\$', 10, null),
  'DE': VatFormat('DE', '^[0-9]{9}\$', 9, null),
  'DK': VatFormat('DK', '^[0-9]{8}\$', 8, null),
  'EE': VatFormat('EE', '^[0-9]{9}\$', 9, null),
  'ES': VatFormat('ES', '^[A-Z0-9][0-9]{7}[A-Z0-9]\$', 9, null),
  'FI': VatFormat('FI', '^[0-9]{8}\$', 8, null),
  'FR': VatFormat('FR', '^[0-9A-HJ-NP-Z]{2}[0-9]{9}\$', 11, null),
  'GB': VatFormat('GB', '^([0-9]{9}|[0-9]{12}|GD[0-9]{3}|HA[0-9]{3})\$', 12, null),
  'GR': VatFormat('EL', '^[0-9]{9}\$', 9, null),
  'HR': VatFormat('HR', '^[0-9]{11}\$', 11, null),
  'HU': VatFormat('HU', '^[0-9]{8}\$', 8, null),
  'IE': VatFormat('IE', '^([0-9]{7}[A-W]|[0-9][A-Z*+][0-9]{5}[A-W]|[0-9]{7}[A-W][A-IW])\$', 9, null),
  'IT': VatFormat('IT', '^[0-9]{11}\$', 11, null),
  'LT': VatFormat('LT', '^([0-9]{9}|[0-9]{12})\$', 12, null),
  'LU': VatFormat('LU', '^[0-9]{8}\$', 8, null),
  'LV': VatFormat('LV', '^[0-9]{11}\$', 11, null),
  'MT': VatFormat('MT', '^[0-9]{8}\$', 8, null),
  'NL': VatFormat('NL', '^[0-9]{9}B[0-9]{2}\$', 12, null),
  'PL': VatFormat('PL', '^[0-9]{10}\$', 10, null),
  'PT': VatFormat('PT', '^[0-9]{9}\$', 9, null),
  'RO': VatFormat('RO', '^[0-9]{2,10}\$', 10, null),
  'SE': VatFormat('SE', '^[0-9]{12}\$', 12, null),
  'SI': VatFormat('SI', '^[0-9]{8}\$', 8, null),
  'SK': VatFormat('SK', '^[0-9]{10}\$', 10, null),
  'XI': VatFormat('XI', '^([0-9]{9}|[0-9]{12}|GD[0-9]{3}|HA[0-9]{3})\$', 12, null),
};
